name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
  # - run: find lib types -type f -exec sha1sum '{}' '+' | tee lib-hashes.txt
    - run: npm run build
      env:
        CI: true
  # - run: sha1sum --check lib-hashes.txt
    - run: npm test
