name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
    env:
      CI: true

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x86
    - run: npm install
    - run: npm run clean:lib 
    - run: npm run build:build-codegen 
    - run: npm run build:run-codegen 
    - run: npm run clangformat 
    - run: npm run prettier:generated 
    - run: npm run build:native
  # - run: npm run build:type-declarations 
  # - run: npm run build:build-generated",
    - uses: actions/upload-artifact@v2
      with:
        name: addon
        path: build/Release
    - run: npm test
