name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: x86
    - run: npm install
    - run: npm run build
      env:
        CI: true
    - run: npm test
